version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/blog:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/blog.conf:/etc/nginx/conf.d/blog.conf:ro
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
